### ISSUE TITLE
Opts are not clear

### ISSUE THREAD

**Issue by flauted** [OpenNMT/OpenNMT-py#1231]
Some of the opts don't make sense. For example, ``opt.enc_rnn_size`` is ``TransformerEncoder``'s ``d_model`` arg. Similar for ``opt.dec_rnn_size``. And, ``opt.encoder_type`` is only relevant when ``opt.model_type`` is text.

I'm happy to take on fixing this. First, I want to generate some discussion on the best way, and other things that could be fixed along the way.

I personally like how Fairseq has each model define a ``add_args`` method. See [this](https://github.com/pytorch/fairseq/blob/master/fairseq/models/lstm.py#L26).

Backwards compatibility is an issue, too. Checkpoints save the opts. If the command line interface is updated, then there needs to be some check for old-style opts and an update to the new one.

**Comment by vince62s** [comment]
I know but this stems from the additions that came along since the very begining of the project.
Trying to maintain backward compatibility and uniformization is not so easy.
To compensate a bit, we created this concept of config.yml file where we can have kind of templates depending on the architecture:
https://github.com/OpenNMT/OpenNMT-py/blob/master/config/config-transformer-base-4GPU.yml

**Comment by flauted** [comment]
Yeah I understand there's historical reasons it's like this now. The config files help, but it's still odd reading it. I think that adding a "hidden" argument like ``--new_style, action="store_true", default=True`` argument would make it easy enough to tell if the opts are old or new. When parsing, if ``--new_style`` is found, then do new parsing. If not, remap the old opts to what they are now and then do new parsing.
