### ISSUE TITLE
I have two gpus, but now I can only use the second GPU. How can I modify the parameters? Thank you

### ISSUE THREAD

**Issue by yueyongjiao** [OpenNMT/OpenNMT-py#1329]

**Comment by flauted** [comment]
On training, ``-world_size 2 -gpu_ranks 0 1``. Translation is single-GPU right now.

**Comment by yueyongjiao** [comment]
> On training, `-world_size 2 -gpu_ranks 0 1`. Translation is single-GPU right now.

I can't use the first GPU, I can only use the second GPU, your method will result in using two GPUs at the same time

**Comment by flauted** [comment]
My bad. If you you have two GPUs but only the second is available, use ``-world_size 1 --gpu_ranks 1``, or that plus setting the environment variable ``CUDA_VISIBLE_DEVICES=1``. You may have to play around with the ``--gpu_ranks`` and ``CUDA_VISIBLE_DEVICES`` arguments since it doesn't always follow PCI order.

**Comment by vince62s** [comment]
recommended setting is cuda_visible_devices=1
world_size 1 gpu_ranks 0

**Comment by zhao1402072392** [comment]
> recommended setting is cuda_visible_devices=1
> world_size 1 gpu_ranks 0

this does not work, it run on the first gpu

**Comment by zhao1402072392** [comment]
recommended setting is cuda_visible_devices=1
world_size 1 gpu_ranks 0
 this doesn't work ,it run on the first gpu
