### ISSUE TITLE
size of trained model

### ISSUE THREAD

**Issue by nikhiljaiswal** [OpenNMT/OpenNMT-py#1374]
Hi,
I have trained a transformer model having 3 layers. The size of trained model is in GB.
For translating a single sentence I have to load the model and translate src file containing a single sentence. Since the size of trained model is huge, I assume the time to load model is more, as a result it takes quite a few time to come out with the translation.
Is there anyway to reduce the model size and store only the parameters required during the inference time?

**Comment by shane-carroll** [comment]
To strip out most of the unnecessary stuff (e.g., optimizer state), you can easily use the `tools/average_models.py` script and specify only a single input model.

```
python tools/average_models.py -m checkpoint.pt -o checkpoint_minimal.pt
```

And if you wanna get your hands dirty, you could save the model to disk in half precision. It'll get cast to fp32 on load so depending on your disk speed this may or may not help with loading time.

Also if you are translating only a single sentence I'd mask the visible GPUs and force CPU computation, since the time to move the model to the GPU is probably longer than the translation time on CPU.

**Comment by nikhiljaiswal** [comment]
@shane-carroll  thanks for your response. I used tools/average_models.py script and my model size reduced from 1 gb to 380mb. that was beneficial.
Coming to your second and third point, where do we need to make the changes in the code. Where is the option to mask the visible GPU ?

**Comment by ymoslem** [comment]
Thanks for the recommendation! Two notes here:

1. You have to move the file `average_models.py` outside of `tools` folder to `OpenNMT-py` folder or you will get an error "onmt module not found" @vince62s 
2. If you are on a CPU-only machine, you have to add `map_location='cpu'` to `torch.load()` to be `m = torch.load(model_file, map_location='cpu')`

**Comment by 1-800-BAD-CODE** [comment]
1. You probably didn't run `python setup.py develop` (or `install`)

2. I'm not a developer of onmt, but IMO that's a bug and should have it's own issue (and maybe submit the corresponding PR since you have the solution). Model averaging shouldn't require a GPU; moreover it may be faster to use CPU rather than move all models to GPU to average them.
