### ISSUE TITLE
<unk> or UNK token for preprocessing of gigaword dataset

### ISSUE THREAD

**Issue by mrpega** [OpenNMT/OpenNMT-py#1485]
I noticed that <unk> tokens are used in Gigaword dataset and there's a blogpost here:
https://medium.com/the-artificial-impostor/build-a-summarization-system-in-minutes-5f10c141bfe6
that says we must replace the <unk> to UNK but OpenNMT-py internally uses <unk> token, which means it will cause a mismatch in vocab.

What is the right procedure? Thanks all!

**Comment by vince62s** [comment]
@pltrdy what's the best practice for this.

**Comment by pltrdy** [comment]
We mostly do as suggested: replace <unk> in dataset to `UNK`. It may sound weird, but actually, it's two different notions: `<unk>` is for tokens that are internally unknown (in the model), but the model should be able to generate/copy `UNK` since it's not a very rare token in the dataset.

As you said @mrpega it wont match in the vocab, but it make sense.
