### ISSUE TITLE
Need help understanding the transformer layer cached states

### ISSUE THREAD

**Issue by weiyengs** [OpenNMT/OpenNMT-py#1551]
Hi,
I was looking through the codes of the transformer decoder implementation and noticed that it keeps a dictionary of states which acts as like a cache for N layers:

https://github.com/OpenNMT/OpenNMT-py/blob/0b14c26c9c5d8f25bb415b112352b72299a2ff07/onmt/decoders/transformer.py#L218

But I don't see the reason why we have to "cache" it. Is it because we will be using the same information for a number of time steps when decoding? Can someone elaborate on that?

Does each layer refer to 1 "block" in this illustration:

![](https://s3-ap-south-1.amazonaws.com/av-blog-media/wp-content/uploads/2019/06/Screenshot-from-2019-06-17-19-53-10.png)

Thanks!!

**Comment by francoishernandez** [comment]
Hi @weiyengs 

The logic for the caching mechanism is a bit more explicit in [onmt.modules.multi_head_attn](https://github.com/OpenNMT/OpenNMT-py/blob/0b14c26c9c5d8f25bb415b112352b72299a2ff07/onmt/modules/multi_headed_attn.py#L132).
Basically the cache is used to limit computations in the decoder. Without cache, we would have to recompute full attention states at each step of the decoder. With the cache it allows to only decode the required states, because previous states are already known.

Found [this blog post](https://tunz.kr/post/4) on the topic:

> "We can optimize autoregressive steps by caching unnecessary repetitive computations. Decoding steps expand targets one by one after getting output from Transformer and feed the expanded targets until we reach the EOS token. The point here is that inputs never changes. We only have to get Encoder Output once and reuse it for the rest decoding steps, which improves decoding speed 1.33 times faster. Furthermore, the Encoder Output is used to get K and V value for encoder-decoder attention. We can also keep these values and reuse them, which makes it 1.42 times faster."
