### ISSUE TITLE
Is this normal that beam.done is False?

### ISSUE THREAD

**Issue by shuaihuaiyi** [OpenNMT/OpenNMT-py#1621]
I find that after the loop (https://github.com/OpenNMT/OpenNMT-py/blob/2a118d6273539fd2ea39c16d2687dacd60075e94/onmt/translate/translator.py#L683) is finished when `step` exceeds `max_length`, `beam.done` may still be `False`, and there are empty lists in `beam.predictions`. This will further raise a `IndexError: list index out of range` at https://github.com/OpenNMT/OpenNMT-py/blob/2a118d6273539fd2ea39c16d2687dacd60075e94/onmt/translate/translation.py#L95

This might be a bug, please take a look at it.

**Comment by francoishernandez** [comment]
Hi @shuaihuaiyi 
This sounds like #1559 or [this](http://forum.opennmt.net/t/translation-doesnt-continue-after-specific-number-of-statements/3167) but I'm not sure about your suggestion.

In every `beam.advance()` we call `ensure_max_length`:
https://github.com/OpenNMT/OpenNMT-py/blob/2a118d6273539fd2ea39c16d2687dacd60075e94/onmt/translate/beam_search.py#L203
which ensures all `beam.is_finished` if not already:
https://github.com/OpenNMT/OpenNMT-py/blob/2a118d6273539fd2ea39c16d2687dacd60075e94/onmt/translate/decode_strategy.py#L94-L98
Then, `update_finished` is called and because every beam will be finished the following condition will be validated:
https://github.com/OpenNMT/OpenNMT-py/blob/2a118d6273539fd2ea39c16d2687dacd60075e94/onmt/translate/beam_search.py#L257-L259

Maybe I'm missing something.
@flauted @guillaumekln any idea about this one?

**Comment by guillaumekln** [comment]
Is there a way to reproduce this? Not sure what conditions trigger the error.

**Comment by shuaihuaiyi** [comment]
The reproduction of this error is unstable. Sometimes the translation process can finish but sometimes cannot, even with same checkpoint and same options. This is weird so I study it a little further, and find that it may be related with a bug of pytorch 1.3 (https://github.com/pytorch/pytorch/issues/29106). 
https://github.com/OpenNMT/OpenNMT-py/blob/2a118d6273539fd2ea39c16d2687dacd60075e94/onmt/translate/beam_search.py#L213
After trying the workground mentioned in https://github.com/pytorch/pytorch/issues/28747, this error haven't happened again for a while. I will keep monitoring and if it happens again I will let you know.
