### ISSUE TITLE
Does OpenNMT-py support training with pretrained cross-lingual embeddings?

### ISSUE THREAD

**Issue by lihongzheng-nlp** [OpenNMT/OpenNMT-py#1749]
Hi all,  when I train OpenNMT-py with the pretrained embeddings, I come out a stupid question: **does it support training with pretrained cross-lingual embeddings(CLM)**?  I've got the cross-lingual embeddings with MUSE, and wondering whether I can add them in the training. I know XLM is popular with the CLM settings.

By the way, another question is **does OpenNMT-py also support pretrained embeddings trained with fasttext?**  Because I found that the choices of the parameter `'-type'` in `embeddings_to_torch.py` are limited to Glove(default) or word2vec. 

I'd like to thank everyone who can solve my questions!

**Comment by DiegoMoussallem** [comment]
Hi @lihongzheng-nlp for your first question, I think you can make it happen by using the option -emb_file_both then you will be able to use cross-lingual on both sides. For the second question, yes, you can use fastText because one of its outputs is .vec (apart from .bin) which is equal to the one used in word2vec. 

I hope it helps
