### ISSUE TITLE
Update to agree with new TorchText

### ISSUE THREAD

**Issue by JianyuZhan** [OpenNMT/OpenNMT-py#189]
While running train.py, using the data in data/ directory, and following the Quickstart procedure,  it quickly fails with below error:

File "/home/myhome/data/code/OpenNMT-py/onmt/Models.py", line 206, in forward
    packed_emb = pack(emb, lengths)
ValueError: lengths array has to be sorted in decreasing order

pack_padded_sequence requires the lengths argument to be sorted by decreasing order.

**Comment by srush** [comment]
Hmm, looking into this, wonder if torchtext changed.

**Comment by jekbradbury** [comment]
Torchtext changed on master (our development branch), but the version installed by your requirements.txt file should still be fixed since we haven't tagged a new version for pypi.

**Comment by jekbradbury** [comment]
Discussion here https://github.com/pytorch/text/pull/95; I'm going to take a look at it again soon

**Comment by srush** [comment]
thanks @jekbradbury . We're live with `torchtext` now, it's been great. Let us know when we should fix things.

**Comment by jekbradbury** [comment]
The current plan is to release an updated tag in a couple weeks with this change, one or two other minor breaking changes, new built-in datasets, and (backwards-compatible) support for fields that can also reverse their tokenization/preprocessing steps (including a simple reversible tokenizer I'm calling revtok that optionally supports subwords). We'll let you know when it's ready and won't release it to pypi until it's confirmed non-breaking for you.

**Comment by srush** [comment]
Awesome. 

While we have you, there are two other random feature that I think we would love, I can make issues. 1) Auto-padding of non-vocab fields (we do it now with post-processing). 2) Ability to have non-tensor objects associated with a batch. The second comes up because we are using dynamic dictionaries associated with each source sentence. We hack around it now, but I would love to have a list of dicts in the batch.

**Comment by jekbradbury** [comment]
Yes, both of those sound like good ideas in general!

The second one is definitely a missing feature, which should be pretty easy to achieve. There's [this PR](https://github.com/pytorch/text/pull/51) from our intern Alexander, which would have used `field=None` to represent data that should be attached to a batch as a raw list of objects. We didn't merge it because it would have broken the existing use of `field=None` to represent "ignore this column in CSV/TSV source data," but we can replace it with `field=RawField()` or the like.

The first sounds like something I intended to work (glancing at the Batch/Field implementation, non-vocab-having Fields should have `pad` called like normal and simply skip the `stoi` lookup in `numericalize`, so something else must be missing/not working as intended. Maybe open an issue there? I'll make sure to add the second feature you mention for the next tag and find a fix for the first one.

**Comment by jekbradbury** [comment]
Finally released [v0.2.0](https://github.com/pytorch/text/releases/tag/v0.2.0) (also on PyPI) that rationalizes the original problem from this thread and introduces `RawField` while also fixing use of floats/ints as data in a sequential `Field`.

**Comment by JianyuZhan** [comment]
Thanks for the fix @jekbradbury!  `sort_within_batch` guards the `decresing-sorting-in-batch` behavior, which defaults to be `None`.  This means the old code still breaks even updated to `v0.2.0`(user has to indicate`sort_within_batch`).  I think this semantics should be done in `torchtext`, and the user of needs only provide a `sort_key`? This also keeps compatibility of old user code(user only needs update to the latest torchtext).

**Comment by raviolli** [comment]
Is this issue fixed? I'm getting the same error: 
  File "/home/ravi/anaconda3/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 79, in pack_padded_sequence
    raise ValueError("lengths array has to be sorted in decreasing order")
ValueError: lengths array has to be sorted in decreasing order


Processing torchtext-0.2.0-py3.6.egg
Copying torchtext-0.2.0-py3.6.egg to /home/ravi/anaconda3/lib/python3.6/site-packages
Adding torchtext 0.2.0 to easy-install.pth file


Thanks
