### ISSUE TITLE
Load and keep small dataset in memory when training

### ISSUE THREAD

**Issue by AmitMY** [OpenNMT/OpenNMT-py#1930]
I'm experimenting with training a various number of training examples to see the effect on accuracy for me.
Its a very easy task, so it makes sense to even use 69 examples.

When I use such small number of examples, the training script just loads the dataset many many times.

Is there a way to tell the script to keep the data in memory? My GPU utilization is very very small, and I believe its because its spending most time on loading data.

![image](https://user-images.githubusercontent.com/5757359/99034497-fbc80580-2585-11eb-9243-57ba9c38e482.png)

**Comment by francoishernandez** [comment]
Indeed, using so few data is quite an edge use case here.
Since you're using the `legacy` version (< 2), you may try modifying the [`DatasetLazyIter`](https://github.com/OpenNMT/OpenNMT-py/blob/585499a4509b1c2dac7683b7588f3f544f89119e/onmt/inputters/inputter.py#L808) class to retain your data in memory instead of loading it again and again.
If you're planning on switching to 2.0, you may want to have a look at the [`ParallelCorpus`](https://github.com/OpenNMT/OpenNMT-py/blob/82f5d37b4d79844946405d1a7a9493e31796aa3c/onmt/inputters/corpus.py#L107) class. (This one may be easier to modify if you're not comfortable with the codebase.)

If you're willing to make this configurable through a flag without breaking current functionality, we'd be willing to accept a PR as it may be useful for others.

**Comment by Zhw098** [comment]
Hi, I also have the same question, How did you finally solve this problem?
Thanks!

**Comment by francoishernandez** [comment]
@Zhw098 as stated above the easiest solution is to modify the [`ParallelCorpus`](https://github.com/OpenNMT/OpenNMT-py/blob/82f5d37b4d79844946405d1a7a9493e31796aa3c/onmt/inputters/corpus.py#L107) class to add some caching for instance. E.g. in the `load` method only read the file once, and store it in some `self.cache` for instance, and then reuse it.

Else, if you're not comfortable with python, you can always make a bigger version of your dataset by concatenating it N times so that it will load less frequently...
