### ISSUE TITLE
Failed to load pretrained model

### ISSUE THREAD

**Issue by KYRIEZX** [OpenNMT/OpenNMT-py#1942]
My script is as, and the model I use is downloaded from [this:](https://opennmt.net/Models-py/)
`python translate.py --model available_models/en-de.pt --src ../en-de.txt --random_sampling_topk 10 --random_sampling_temp 0.5 --beam_size 1 --gpu 6`
When I use English-German - Transformer
![image](https://user-images.githubusercontent.com/56826566/99498469-7774e880-29b2-11eb-933f-c9164ab2c5ac.png)

While I use German-English - 2-layer BiLSTM :
![image](https://user-images.githubusercontent.com/56826566/99498435-675d0900-29b2-11eb-9d43-a2502c926e78.png)

**Comment by francoishernandez** [comment]
Looks like your model file is corrupt. Did you extract the archive you downloaded?

**Comment by KYRIEZX** [comment]
> Looks like your model file is corrupt. Did you extract the archive you downloaded?
> Edit: the LSTM model is not compatible with OpenNMT-py 2.0 yet. We'll have to update it. But the Transformer one should work.
> Edit2: the LSTM model was just updated, you may download it again.

Thanks for answering. It seems to work after reloading the transformer model. But the output texts are like this:
![image](https://user-images.githubusercontent.com/56826566/99511090-c75bab80-29c2-11eb-8133-8efa7dc9b4dd.png)
Is this common?

**Comment by francoishernandez** [comment]
This is because the model was trained with [sentencepiece](https://github.com/google/sentencepiece) tokenization.
There is an example script on how to prepare data using sentencepiece here: https://github.com/OpenNMT/OpenNMT-py/blob/master/examples/scripts/prepare_wmt_data.sh
I encourage you to search the [forum](https://forum.opennmt.net) to learn more.
