### ISSUE TITLE
How to do joint alignment translation traininig?

### ISSUE THREAD

**Issue by michelleqyhqyh** [OpenNMT/OpenNMT-py#2123]
![config](https://user-images.githubusercontent.com/45490378/142835088-8201fc0d-2db5-4e04-aee7-ba1ea9bb31e6.png)
![error](https://user-images.githubusercontent.com/45490378/142835101-12d8297c-7256-4c0a-9af2-b9db4d7e6e89.png)
I used version 2.2.0. These are my config and error. Do you know how to make it run?

**Comment by francoishernandez** [comment]
@Zenglinxiao your input might be useful here :)

**Comment by Zenglinxiao** [comment]
@michelleqyhqyh  Could you try running it with `--max_generator_batches 0`?

**Comment by michelleqyhqyh** [comment]
> @michelleqyhqyh Could you try running it with `--max_generator_batches 0`?

Thank you. It works. By the way, if I pointed the specific alignment files like in the picture, what should I give the parameter "-alignment_head", should it be 1 or other？I don't know whether my tack belongs to a surpervised task or an average task.

**Comment by michelleqyhqyh** [comment]
@ZenglinxiaoThank you. It works. By the way, if I pointed the specific alignment files like in the picture, what should I give the parameter "-alignment_head", should it be 1 or other？I don't know whether my tack belongs to a surpervised task or an average task

**Comment by Zenglinxiao** [comment]
Since you are providing an external alignment file, that suggests you want to use that as external knowledge to guide the model training, a.k.a guided alignment training. Then you may want to specify `--alignment_head 1` to force one head of layer `--alignment_layer  -2` to specialize itself in alignment tasks, that is the practice described in the original paper. You can also take other value of course. Please do read the original paper for detail.

Related source code as follows: https://github.com/OpenNMT/OpenNMT-py/blob/2d2445b11091ff4ef837444f7db7a107ee454b09/onmt/decoders/transformer.py#L106-L112
