### ISSUE TITLE
Reproducing WebNLG Challenge 2017 on OpenNMT-py

### ISSUE THREAD

**Issue by dariodellamura** [OpenNMT/OpenNMT-py#2128]
Hi guys, I'm Data Science student and i'm learning to use OpenNMT-py for my master degree thesis. 

I reproduced the challenge with the old deprecated repository, now I would like to replicate it with the updated repository (as I will need it for a similar task within my thesis).

I am now approaching the NLP field, but I am not very clear about some things:

- since it is not a translation task, is it necessary to build a vocabulary like in the machine translation OpenNMT-py tutorial?

- The epochs command I noticed has been deprecated, now it works with train_steps, however I am not clear about the "conversion", so to speak. With the old repository the number of epochs to train the model with was 13. I tried this by  looking at old problems from these repositories: default train_steps (100000) / deault batch_size (64) * 13 (epochs number of the old repository) = 20313.

is this reasoning correct? Thanks everyone for your attention.

**Comment by francoishernandez** [comment]
> since it is not a translation task, is it necessary to build a vocabulary like in the machine translation OpenNMT-py tutorial?

The fact that we need to build a vocabulary has nothing to do with translation. The vocabulary is needed to map `tokens` to `ids`.

> The epochs command I noticed has been deprecated, now it works with train_steps, however I am not clear about the "conversion", so to speak. With the old repository the number of epochs to train the model with was 13. I tried this by looking at old problems from these repositories: default train_steps (100000) / deault batch_size (64) * 13 (epochs number of the old repository) = 20313.

Here you assume that 100k steps == 13 epochs, which does not make sense since the number of training steps in an epoch depends on your dataset size.

It will depend on your configuration and data. 
For simple cases, basically "true" batch_size = batch_size * num_gpus * accum_count. (But the notion of epochs is not really relevant when you start to train models with several datasets, with different weights etc.)
Also, `tokens` batch size is more efficient than `sents`, which would make the epoch/step matching even less easy.

Though, in the latest versions we added some logging of a counter of the number of times each dataset is loaded, which may help you get a rough idea about a number of epochs. 

Finally, such topics are not really issues but discussions that should live [on the forum](https://forum.opennmt.net/) rather than here. You might want to browse the various topics there, as a lot of topics and frequent questions are already covered.
