### ISSUE TITLE
some question about openNMT

### ISSUE THREAD

**Issue by Andrewlesson** [OpenNMT/OpenNMT-py#2137]
The openNMT model can not translate the number string into Chinese character string well. Because the number in the number string is 0 to 9, the model can only learn the relationship between these sequences to generate Chinese string. Is there any good method or model to solve this problem?  Is there a character level based machine translation ？
example：  src:  42682947422    tgt: 我们  一起  吧

**Comment by Zenglinxiao** [comment]
**PLEASE DO NOT RAISE THESE COMMON DISCUSSION HERE, DO IT ON THE FORUM!
Only raise Issues for bug reports or code-related questions!**
-------------------------
I think you should properly formulate your problem before making an assertion. I am not sure fully understand your question, but it seems you want to generate a Chinese sequence given a digit sequence.
Not sure why you want to do that, but if so, nothing prevents it with a seq2seq model. And seq2seq is the main focus of OpenNMT.
With a seq2seq model, you can map between any type of sequences if the problem is well defined, the model has enough compatibility, and data volume is decent for the model to fit. The most common task for seq2seq is translation, but under the hood, the model actually learns a function to map a sequence of digits to another sequence of digits, and the digit, in this case, is the index of the word in each side pre-calculated dictionary.

So, your problem is a seq2seq task. You can do whatever you want, character level, subword level, or word level providing there is some hidden pattern between the digit side and text side.
