### ISSUE TITLE
Comparison of OpenNMT-tf and OpenNMT-py 

### ISSUE THREAD

**Issue by nashid** [OpenNMT/OpenNMT-py#2151]
I have to use a Transformer network for a machine translation task. I decided to go with OpenNMT. But which framework should I choose between `OpenNMT-tf` and `OpenNMT-py`?  

I am not aware of any direct comparison between `OpenNMT-tf` and `OpenNMT-py` with the Transformer model for a machine translation task. I presume they would yield a similar result.

But would really appreciate it if anyone can shed light on which works better for an NMT task so that I can make an informed decision.

**Comment by guillaumekln** [comment]
See https://opennmt.net/FAQ/#which-opennmt-implementation-should-i-use. They perform similarly in terms of final translation quality.

You should also consider that they share the same inference engine: [CTranslate2](https://github.com/OpenNMT/CTranslate2). So the choice of the training framework is not very important since you can then run all models in a common inference platform.

Feel free to ask more questions on the [forum](https://forum.opennmt.net/).
