### ISSUE TITLE
Using custom encoder and/or decoder

### ISSUE THREAD

**Issue by kleag** [OpenNMT/OpenNMT-py#2403]
Hi,
We are trying to use a custom encoder and decoder in our OpenNMT-py model. We found the following answer:
https://forum.opennmt.net/t/how-to-build-my-own-model-using-opennmt-py/3222
which suggests to modify `onmt/decoders/__init__.py`.

But we find quite unsatisfactory to have to modify files from the virtual environment or even worse, from the system.

Is there a way to add such a custom class, maybe with a decorator, something like `@register_encoder`? I saw that it exists for data transformation (`@register_transform`) if I understand well but I cannot find the equivalent for other parts.

**Comment by vince62s** [comment]
I am not sure to fully undertstand your issue with modifying the `onmt/decoders/__init__.py` since you have to add your own code anyway. Regarding the decorator, yes it would be possible but requires some dev that I have in my roadmap. A PR would be very welcome though.
Out of curiosity, what kind of encoder or decoder would like to add or modify ?
