### ISSUE TITLE
Line-by-line paper citations

### ISSUE THREAD

**Issue by srush** [OpenNMT/OpenNMT-py#248]
OpenNMT now includes implementation of probably 12 papers or so. We should have a standard practice for citing papers into the code with arxiv links.

 Does anyone have a suggestion for how to do this in a consistent way for future reference?

**Comment by sebastianGehrmann** [comment]
I don't think in-code citations might be the most effective way. My reasoning is that some papers require touching more than one place in the code and that beginners do not know which parts those are or how to find them.
I propose that we work with citations in the opts file instead since everyone needs to look there anyway. Before every option, we could note the paper that the particular option implements. Below a proposed format:

```
# RNN Options
# Transformer: Attention is all you need (https://arxiv.org/abs/1706.03762)
parser.add_argument('-encoder_type', type=str, default='rnn',
                                     choices=['rnn', 'brnn', 'mean', 'transformer', 'cnn'],
                                      help="""Type of encoder layer to use.""")
```

In the long term, we should probably adjust http://opennmt.net/OpenNMT/ to include descriptions of our code. With some significant effort, we could also write a case study that includes (1) the difference  between lua/py versions, (2) a description of what system to use. This one we should not do, before we arrive at a stable 1.0 version to not have more overhead.

**Comment by srush** [comment]
That's a very nice idea. Maybe we can have forward pointers to the places in the code as well though now that we have removed direct usages of `opt` from the code base.

**Comment by sebastianGehrmann** [comment]
I agree, we should have pointers. Since line numbers are changing, we could point to files, classes, or specific functions. How about this?

```
# RNN Options
# Transformer: Attention is all you need (https://arxiv.org/abs/1706.03762)
#              modules/Transformer.py
parser.add_argument('-encoder_type', type=str, default='rnn',
                                     choices=['rnn', 'brnn', 'mean', 'transformer', 'cnn'],
                                      help="""Type of encoder layer to use.""")
```

**Comment by srush** [comment]
I ended up doing this using :cite:`` and ref file in docs.
