### ISSUE TITLE
Why StackedLSTM?

### ISSUE THREAD

**Issue by Yevgnen** [OpenNMT/OpenNMT-py#389]
Hi, I might be missing something, but the docstring of `StackedLSTM` says `Our own implementation of stacked LSTM. Needed for the decoder, because we do input feeding.`.

What is it different `torch.nn.LSTM` with a `num_layers > 1`? Thank you.

**Comment by JianyuZhan** [comment]
Because we do `Input Feed`, which takes into account the past attention info, by concatenating the attentional output with the input in next time step(See https://arxiv.org/pdf/1508.04025.pdf Sec 3.3).

So we need a custom version of `StackedLSTM` , which takes input of size `input_size + hidden_size` for first layer,  while taking input of size `input_size` for the subsequent layers.  This is not standard `torch.nn.LSTM` behavior.

Also look at this schematic explanation, note the "dotted lines".

![opennmt-py-issue](https://user-images.githubusercontent.com/649042/33115564-1019be4c-cf27-11e7-96c2-2406bbaef9fc.png)

**Comment by Yevgnen** [comment]
Thank for your reply. Why the input size of subsequent layers isn't `hidden_size`?

**Comment by JianyuZhan** [comment]
Oh, yep, typo.  The input size of subsequent layers is `hidden_size`.

**Comment by Yevgnen** [comment]
Then what's wrong with `nn.LSTM` for input feeding?

**Comment by JianyuZhan** [comment]
The difference is in the ` forward` process.  In `nn.LSTM`, you give the input, it flows all time steps and return the output and hidden state of the final step. It can't do the "concatenation" magically for you. So we need a custom "StackedLSTM", which run for one time step for each call, and we do the "concatenation" in `InputFeedRNNDecoder`.

**Comment by JianyuZhan** [comment]
Right, this method looks semantically correct. And I tried to dig the git history for the incorporation of this code, see e323c205. It did use `nn.LSTM` before. But it doesn't mention the reason.

**Comment by ketranm** [comment]
I was there when the code use nn.LSTM. Unfortunately using `nn.LSTM` is overkill if it's called for only 1 time step. There were some memory and speed issue when nn.LSTM was used. In this regard, using `nn.LSTMCell` is more optimal.

**Comment by Yevgnen** [comment]
@ketranm Thanks for you details!
