### ISSUE TITLE
Loss is not dropping during the epoch, drops at start of the next epoch

### ISSUE THREAD

**Issue by maksymbevza** [OpenNMT/OpenNMT-py#420]
Hello

I’ve trained quite a few models on OpenNMT-py and this is the train ppl that I have:

<img width="524" alt="screen shot" src="https://user-images.githubusercontent.com/1665959/33673509-9af13e3e-dab5-11e7-9d1d-2744bfc524c8.png">

Each point on a chart is an average PPL for 50 mini-batches.
The perplexity is not changing. During the epoch it even increases sometimes. On the start of each epoch you can see a significant drop in PPL.

Even though the perplexity goes down and validation perplexity also goes down on the next epoch, I still have a feeling that at the end of the day I’m losing in accuracy.

Could you please tell me where possible problems could be?

**Comment by JianyuZhan** [comment]
I assume this is not the problem of code, but rather the black-box problem of the model.

**Comment by dcasbol** [comment]
I've recently found the same behaviour in a problem I'm working on. It turns out it's a consequence of both having a big number of output classes and too large word embeddings. The slight increase and sudden drop is caused by an almost per-sample learning, which doesn't precisely promote generalisation.
