### ISSUE TITLE
Lexical constraints and phrase table, replace_unk_tagged

### ISSUE THREAD

**Issue by i55code** [OpenNMT/OpenNMT-py#427]
Hi, is there an equivalent of -lexical_constraints and -phrase_table, and -replace_unk_tagged in OpenNMT-py as in OpenNMT torch code? 

Those features are important, thanks!

**Comment by srush** [comment]
We unfortunately do not have these yet. Happy for contributions.

**Comment by PR-Iyyer** [comment]
So, can you please help me with how to customise the code in OpenNMT-py so that we can use -lexical_constraints and -phrase_table features??

**Comment by srush** [comment]
Sure. All of this happens in this file here `https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/Translation.py` If you want to use your own phrase table, modify this file to do something different than the standard `replace_unk` behavior. 

For instance, is you have a special "unk_ne" in your vocab, add an if statement 'if tokens[i] == "unk_ne":' on this line.

https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/Translation.py#L41

And then instead of replacing with src_raw, replace based on the dictionary.

**Comment by PR-Iyyer** [comment]
Thanks, but the line  which u mentioned is having tokens[i] as unk. So how can i do that comparison. ? I think it is coming from predicted values only and here, we need to edit from where pred is coming.. Am i on the right track?

**Comment by PR-Iyyer** [comment]
Thank you, I understand that. But even src is reproduced with unknown. How come that is happening? How to resolve?

**Comment by srush** [comment]
src has unks, but src_raw should not have unknowns it in.

**Comment by SkyAndCloud** [comment]
@srush I think the [doc](http://opennmt.net/OpenNMT-py/options/translate.html) may be disleading because `-replace_unk` doesn't support phrase_table yet. As I seen, `-replace_unk` option select source word with highest attention weight to replace unk in target, which means you haven't implement vanilla approach in `Addressing the Rare Word Problem in Neural Machine Translation`.

**Comment by SkyAndCloud** [comment]
@PR-Iyyer I think this feature would be very important. Could you provide a contribution?

**Comment by eduamf** [comment]
I have included a protect_preprocess.py and adapted preprocess.py and inputter.py to do according the topic "Special characters" in http://opennmt.net/OpenNMT/tools/tokenization/ to protect sequence contents.

In case of complete phrases or sentences. my problem is limited to those that are not in the same expected alphabet at the origin. But if you can identify other cases, then you can protect the entire sentence.

However, to implement that using Flask-RESTful, I'll have to make more adaptations.

I think that OpenNMT seems to be richer in tokenization options than OpenNMT-py.

**Comment by guillaumekln** [comment]
For the REST server, you can use the OpenNMT tokenizer by setting `pyonmttok` in the tokenizer type field:

https://github.com/OpenNMT/OpenNMT-py/blob/master/available_models/example.conf.json#L15

It supports protected sequences out of the box. See the documentation:

https://github.com/OpenNMT/Tokenizer/blob/master/docs/options.md
