### ISSUE TITLE
Question about decoder

### ISSUE THREAD

**Issue by playma** [OpenNMT/OpenNMT-py#429]
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L343

Can I ask what is `rnn_output` and `hidden` the output of `self.rnn`
And In L344, why OpenNMT pass `rnn_output` to `self.attn` instead of `hidden`

I found that it passes `hidden` in the document, so I am confused.

<img width="547" alt="screen shot 2017-12-09 at 9 31 28 pm" src="https://user-images.githubusercontent.com/7677470/33796074-61d56b46-dd28-11e7-872f-265fffd9ea70.png">

**Comment by srush** [comment]
Yeah, so that diagram is not completely accurate. When you have a general RNN there is one part that is passed as the output (up in that diagram) and another that is used for the next time step (over in that diagram). For basic Elman RNNs those are the same (h_t), for LSTMs they may be different (c_t, h_t). `rnn_output` is h_t, `hidden` is (c_t, h_t), and is used for the next time step.
