### ISSUE TITLE
RNN decoder without attention

### ISSUE THREAD

**Issue by jsedoc** [OpenNMT/OpenNMT-py#574]
I'm sure this is a stupid question, but I can't figure out how to turn attention off.

**Comment by srush** [comment]
Ugh, we actually don't have this implemented in an easy way. It shouldn't be hard to do, but at the moment you have to just shortcircuit the call to attention manually. 

e.g. 

run with input_feed = 0

and 

Change this line: 
https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L402
to just set 

`decoder_outputs = rnn_output`

If that works for you, send us a PR.

**Comment by pinzhenliao** [comment]
@srush yes, your solution works. just delete L402 and L407, and set decoder_outputs = rnn_output

many thanks

**Comment by fracting** [comment]
Hey @vince62s, could I get some help please, you closed https://github.com/OpenNMT/OpenNMT-py/issues/426 and this issue but I still can't find a way to turn off attention. Is it documented in anywhere, or is there no plan to support? Thanks!

**Comment by vince62s** [comment]
What did you try so far ?
Attention is calculated here: https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/decoder.py#L235
Why don't you follow srush's comment ?

There is no PR because it seems very few people needs this use case. What is yours ?

**Comment by fracting** [comment]
@vince62s thanks for quick response.

> What did you try so far ?

I tried:
1. Looked at the OpenNMT document for an argument to disable attention but couldn't find one.
2. Followed https://github.com/OpenNMT/OpenNMT-py/issues/426 and navigate to the code location at https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/Models.py#L259, however the source code was refactored and the code location is invalid
3. Explored the git commit history between July 1st to Aug 8 to see if there is any pull request relevant to this issue, but I couldn't find any.

> Why don't you follow srush's comment ?

I didn't try because in https://github.com/OpenNMT/OpenNMT-py/issues/574#issuecomment-388629298  someone else reported having some additional problem, I am still confused.

> There is no PR because it seems very few people needs this use case. What is yours ?

Fair enough. My use case is special. I'm experimenting on a new way of training word embeddings, I call it _recursive embedding_

My training dataset is from wiktionary, a typical training sample is like this:

source: I'm going to **B** **U** **Y** my father something nice for his birthday.
target: To obtain (something) in exchange for money or goods

During training, the last encoder output (which is also the first decoder input) will be used to update the embedding vector of `buy`, and the updated embeddings will be used in later iterations when training the encoder-decoder model. I hope the training could converge to a state that every word embedding is equal to its dictionary explanation's sentence embedding, I know this is tricky because we are looking for some sort of fixed-point of high dimensional functions.

For this special reason I hope the last encoder output contains all information representing the meaning of the whole target sentence, that's why attention is not ideal here.

> Attention is calculated here: https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/decoder.py#L235

Thank you, let me leave a similar link with the current commit id so other people can also navigate to the right place even if it got refactored again in the future.
https://github.com/OpenNMT/OpenNMT-py/blob/12558b33dbc7de291a1609456256405ba08456dd/onmt/decoders/decoder.py#L235

**Comment by juhuahuang** [comment]
I do not see this issue has a fix. so I made a PR https://github.com/OpenNMT/OpenNMT-py/pull/1063 to explicitly disable attention. Please let me know if it works for this case. I have applied the change in my project and it works good.
