### ISSUE TITLE
Library Example Bugs.

### ISSUE THREAD

**Issue by nikhiltitus** [OpenNMT/OpenNMT-py#696]
Is the library documentation: http://opennmt.net/OpenNMT-py/Library.html outdated? I was not able to use some of the APIs like optim = onmt.Optim(method="sgd", lr=1, max_grad_norm=2)
optim.set_parameters(model.parameters()) properly. I was getting some errors

**Comment by tulongthienvu** [comment]
I am facing the same issue with the documentation. 
I am newbie to OpenNMT-py and watching the documentation to understand how OpenNMT-py run. I am using PyTorch 0.4.

In the above error, I changed OpenNMT's optim to PyTorch's optim
`optim = torch.optim.SGD(model.parameters(), lr=1.0)`
then this above error no longer occurs.

But when I come to
```
for epoch in range(2):
    trainer.train(train_iter, epoch, report_func)
    val_stats = trainer.validate()

    print("Validation")
    val_stats.output(epoch, 11, 10, 0)
    trainer.epoch_step(val_stats.ppl(), epoch)
```
I encountered this error:
```
Traceback (most recent call last):
  File ".../onmt-test.py", line 69, in <module>
    trainer.train(train_iter, epoch, report_func)
  File ".../OpenNMT-py/onmt/Trainer.py", line 163, in train
    cur_dataset = train_iter.get_cur_dataset()
AttributeError: 'OrderedIterator' object has no attribute 'get_cur_dataset'
```
I also encountered some small errors but I fixed them.
After going to use code in use Example: Translation [http://opennmt.net/OpenNMT-py/extended.html](url), this had some errors in Translate sentences step too.

Can anyone help me to solve these problems or updating the documentation?
Thanks.

**Comment by srush** [comment]
Could you post your errors and fixes? We will get this tested so PRs don't break it.

**Comment by AnnieKLamar** [comment]
I compiled a list of changes necessary to run the example on the Library Example page:

- Instead of `import onmt.io`, use `import onmt.inputters`
- Also need to import onmt.utils
- Instead of `onmt.modules.RNNEncoder`, use `onmt.encoders.RNNEnconder`
- Instead of `onmt.modules.InputFeedRNNDecoder`, use `onmt.decoders.decoder.InputFeedRNNDecoder`
- Instead of `onmt.modules.NMTModel`, use `onmt.models.model.NMTModel`
- Instead of `onmt.Loss.NMTLossCompute`, use `onmt.utils.loss.NMTLossCompute`
- Instead of `onmt.Optim`, use onmt.utils.optimizers.Optimizer
- The training files generated will have the train.1.pt suffix rather than train.pt.
- The validation files generated will have the valid.1.pt suffix rather than valid.pt.
- The argument you pass to `model.set_parameters` should be `model.named_parameters()`, instead of `model.parameters()`

I'm currently stuck on how to train the model. I submitted the error I'm receiving [here](https://github.com/OpenNMT/OpenNMT-py/issues/857).

**Comment by vince62s** [comment]
@AnnieKLamar do you have time to check if #939 works for you ? thanks.
