### ISSUE TITLE
Migrate to pytorch 0.4

### ISSUE THREAD

**Issue by xiadingZ** [OpenNMT/OpenNMT-py#705]
pytorch 0.4 has released, please migrate to 0.4

**Comment by srush** [comment]
Yup, Hi-pri. 

[] - Need to fix detach issue
[] - Need to fix softmax
[] - Need to remove all the Variable calls
[] - Try out the new multi-gpu 
[] - get rid of the cuda calls
[] - Try out `checkpoint`

**Comment by nikhilweee** [comment]
Until then, I think it's a good idea to say that we still use pytorch 0.3.1 in the README?

**Comment by livenletdie** [comment]
Is there an approximate ETA on this? I updated to PyTorch 0.4 for a different project and now OpenNMT is breaking for me :(. I can create another virtualenv for older pytorch version if this porting is going to a while.

**Comment by livenletdie** [comment]
Awesome thanks. Let me give it a try.

**Comment by nikhilweee** [comment]
@David-Levinthal I think #403 is just a workaround to make the current distro work with pytorch 0.4. It only has the minimal changes. This however, is a more complete solution which involves many more [changes](https://github.com/OpenNMT/OpenNMT-py/issues/705#issuecomment-384132016)

**Comment by vince62s** [comment]
The #403 works fine for the first test in test/rebuild_models.sh but the second fails
Traceback (most recent call last):
  File "train.py", line 493, in <module>
    main()
  File "train.py", line 485, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 257, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/Trainer.py", line 185, in train
    report_stats)
  File "train.py", line 103, in report_func
    report_stats.output(epoch, batch + 1, num_batches, start_time)
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/Trainer.py", line 72, in output
    self.n_src_words / (t + 1e-5),
RuntimeError: invalid argument 3: divide by zero at /pytorch/aten/src/THC/generic/THCTensorMathPairwise.cu:88

**Comment by David-Levinthal** [comment]
Nikhilweee, excuse my confusion but the link "changes" in your comment points to this report. Are you saying I should install https://github.com/da03/OpenNMT-py/tree/pytorch0.4?

**Comment by nikhilweee** [comment]
@David-Levinthal By changes I meant srush's checklist https://github.com/OpenNMT/OpenNMT-py/issues/705#issuecomment-384132016, which happens to be the second comment on this issue.

**Comment by da03** [comment]
@vince62s maybe try to cast that to a python number first? Something like `self.n_src_words.data.cpu().numpy() / (t + 1e-5)`

**Comment by David-Levinthal** [comment]
AHHH...a bit of background
I am trying to evaluate/establish a multi framework HW evaluation benchmark
suite that can be used by HW vendors/startups and cloud providers (for
purchase decisions)
https://github.com/David-Levinthal/machine-learning/
see the csv file
so I am a bit desperate on getting something working at ~ top of tree as HW
startups do not have the resources to support anything else
The workaround in 403 ran and produced "nice" output and appeared to
converge but seems to fail to translate.

any prognosis on when a Pytorch 0.4 version might become available..or a
version people would like me to test?
one added comment
I am trying to use the same data sets for TF/NMT, MxNet/Sockeye and
Pytorch/OpenNMT
but using the preprocess .py step for the files given to OpenNMT after
following the preparation outlined by TF/NMT (they were the first ones with
an available source base)
that appears to work for sockeye

so the first two sentences in the src-val file
Die Premierminister Indi@@ ens und Japans tra@@ fen sich in Tok@@ io .
Indi@@ ens neuer Premierminister Nar@@ end@@ ra Mo@@ di trifft bei seinem
ersten wichtigen Auslands@@ besu@@ ch seit seinem Wahl@@ sie@@ g im Mai
seinen japanischen Amts@@ kol@@ legen Shin@@ zo A@@ be in Tok@@ o , um
wirtschaftliche und sicherheits@@ politische Beziehungen zu bes@@ prechen .

which look like the following in the tgt-val file
India and Japan prime ministers meet in Tokyo
India &apos;s new prime minister , Nar@@ end@@ ra Mo@@ di , is meeting his
Japanese counter@@ part , Shin@@ zo A@@ be , in Tokyo to discuss economic
and security ties , on his first major foreign visit since winning May
&apos;s election .

is this formatting usable?

d

**Comment by vince62s** [comment]
@da03  Yuntian, it works with the cast. I still see some warnings, but I guess they will need to be addressed when reviewing the whole thing. Might be worth to update the PR and see if @srush is willing to commit the work around in the meantime, unless soemeone has managed to work on all the requested changes for 0.4
If I get time, I'll try to train a small model and see if translate works fine.

**Comment by David-Levinthal** [comment]
fantastic! is this in the main tree?
did you try translation inference, see issue 725?
d

**Comment by vince62s** [comment]
not sure by what you mean by "main tree". it on https://github.com/Ubiqus/OpenNMT-py master.
Translation ran fine for us but give it a try.

**Comment by David-Levinthal** [comment]
I meant
https://github.com/OpenNMT/OpenNMT-py
will the Ubiqus fork be merged with the one I am listing?
d

**Comment by livenletdie** [comment]
I was trying to use https://github.com/Ubiqus/OpenNMT-py but it seems like it has diverged a fair bit from the baseline repo. In particular, no more epochs but training_steps instead. Is that something the base repo is also moving towards?

**Comment by vince62s** [comment]
Most toolkits use steps now (onmt-tf, marian, t2t, ...) it's more meaningful especially when it comes to big corpus.

**Comment by dreamk73** [comment]
How far along is this update? I tried both the master version and da03's version and still get an error about using detach_() instead of detach(). When I change it in the code I get to the following error:

Traceback (most recent call last):
  File "train.py", line 418, in <module>
    main()
  File "train.py", line 410, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "train.py", line 231, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/data/esther/Projects/lts_experiments/scripts/OpenNMT-pytorch0.4/onmt/Trainer.py", line 180, in train
    report_stats)
  File "train.py", line 95, in report_func
    report_stats.output(epoch, batch + 1, num_batches, start_time)
  File "/data/esther/Projects/lts_experiments/scripts/OpenNMT-pytorch0.4/onmt/Trainer.py", line 67, in output
    self.ppl(),
  File "/data/esther/Projects/lts_experiments/scripts/OpenNMT-pytorch0.4/onmt/Trainer.py", line 48, in ppl
    return math.exp(min(self.loss / self.n_words, 100))
RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #2 'other'

**Comment by SimlaBurcu** [comment]
I have the same problem that @dreamk73 posted. Waiting for the update!

**Comment by vince62s** [comment]
guys, if you want a working repo use our fork for the time being. sorry for the delay.

**Comment by dreamk73** [comment]
I downloaded the Ubiqus fork and have verified that I can run the code now using pytorch 0.4.

**Comment by srush** [comment]
The main branch now supports 0.4, we are working to get most of the other Ubiqus changes in as well.

**Comment by srush** [comment]
Very neat, sorry I have been out of touch. Trying to put some time in the next couple weeks to get all the updates checked and in. In particular the main aim is multi-gpu.

**Comment by David-Levinthal** [comment]
can 771 get looked at?

this blocks the use of openmt for the pytorch entry for the transformer
translation test.

**Comment by srush** [comment]
Yes, will prioritize.

https://github.com/OpenNMT/OpenNMT-py/issues/771

**Comment by David-Levinthal** [comment]
Thank you
