### ISSUE TITLE
The speed of translation is slow

### ISSUE THREAD

**Issue by arvidzt** [OpenNMT/OpenNMT-py#717]
the speed of translation is slow, is there any suggestion to optimize it?
or how can i parallelize the process of translation?

my net is brnn(4 layers) + rnn(4 layers) with beam search size of 3 and enable copynet & dynamic dictionary.

**Comment by arvidzt** [comment]
@tulongthienvu thanks for your advice, I'll try pytorch 0.4, I have already use GPU, do you have any suggestions about the batch size, now I set the batch size :32

**Comment by tulongthienvu** [comment]
@arvidzt It depends on your GPU capacity (such as VRAM). If your GPU VRAM is large, feel free to increase batch size to 64, 128, etc to speed up.

**Comment by devinbostIL** [comment]
I'm using a Tesla Xp, and it did not speed up the translation process, as I mentioned here: https://github.com/OpenNMT/OpenNMT-py/issues/743

**Comment by davidlenz** [comment]
With the standard beam size of 5 it seems i can't go any higher than batch_size = 1, otherwise i'll get an out of memory error after a few batches. Therefore the translation process feels rather slow. 

I'll just write done some numbers here for comparison.

I'm on an GTX1060 with 6GB memory, torch 0.4.0 and python 3.6.
I have 32 GB RAM and i7-7700K Intel CPU on 64Bit Windows.

I use the following command:
` python translate.py -model averaged-10-epoch.pt -verbose -replace_unk -beam_size 5 -src trans_para.txt -batch_size 4 -gpu 0 -output pred_para.txt`

- With beam size =1 and batch_size = 16 we run out of memory after 8 batches.
- With beam size = 1 and batch_size = 8 it processes 904 examples and then runs out of memory.
- With beam_size = 2 and batch_size = 4 we get 908 examples done before oom.
- With beam_size =5 and batch_size = 1, no error message and translating 500 examples takes around 2:10 minutes.

The OOM error message is:

> [2018-06-15 17:11:18,748 INFO]
> SENT 16: ('Th', 'urs', 'day')
> PRED 16: ▁Donnerstag
> PRED SCORE: -0.4979
> 
> THCudaCheck FAIL file=c:\programdata\miniconda3\conda-bld\pytorch_1524549877902\work\aten\src\thc\generic/THCStorage.cu line=58 error=2 : out of memory
> Traceback (most recent call last):
>   File "translate.py", line 33, in <module>
>     main(opt)
>   File "translate.py", line 21, in main
>     opt.batch_size, opt.attn_debug)
>   File "E:\OpenNMT-py\onmt\translate\Translator.py", line 162, in translate
>     batch_data = self.translate_batch(batch, data)
>   File "E:\OpenNMT-py\onmt\translate\Translator.py", line 332, in translate_batch
>     inp, memory_bank, dec_states, memory_lengths=memory_lengths)
>   File "C:\Users\Dlenz\Anaconda3\envs\nmt\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "E:\OpenNMT-py\onmt\modules\Transformer.py", line 329, in forward
>     previous_input=prev_layer_input)
>   File "C:\Users\Dlenz\Anaconda3\envs\nmt\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "E:\OpenNMT-py\onmt\modules\Transformer.py", line 202, in forward
>     mask=src_pad_mask)
>   File "C:\Users\Dlenz\Anaconda3\envs\nmt\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "E:\OpenNMT-py\onmt\modules\MultiHeadedAttn.py", line 126, in forward
>     scores = torch.matmul(query_up, key_up.transpose(2, 3))
> RuntimeError: cuda runtime error (2) : out of memory at c:\programdata\miniconda3\conda-bld\pytorch_1524549877902\work\aten\src\thc\generic/THCStorage.cu:58


Not using the -verbose flag probably already provides a speedup.
The averaged-10-epoch.pt is the [pre-trained en-de model ](http://opennmt.net/Models-py/))and i'm trying to translate the [para-nmt-50m corpus](https://github.com/jwieting/para-nmt-50m). 
Given the size of the corpus and the translation speed, rough estimates suggest it takes ~300 days to translate the full corpus. [Wieting et al. (2017)](https://arxiv.org/abs/1711.05732) reported that they used > 10.000 (~416 days) GPU hours to translate the original corpus.


Some questions:

- Are these numbers what is to expect or is there a problem on my end?
- How important is a decent size for the beam search? Where is the offset between translation improvements and computational burden? I feel at least 2 or 3 steps during beam search should be included.
- I have access to an 1080-TI, is it worth the speed-up? What improvement in speed could i possibly expect?
- Can someone share experiences with the pre-trained en-de model?

Thanky you! Any suggestions are greatly appreciated.

**Comment by vince62s** [comment]
pull the latest code and try the -fast flag.

**Comment by mingchen62** [comment]
Using im2text, and '-fast' flag,  and got this:
OpenNMT-py/onmt/translate/translator.py", line 326, in _fast_translate_batch
    assert data.data_type == 'text'
AssertionError

Any idea to get it working with data_type = 'img'? thanks

**Comment by guillaumekln** [comment]
A PR is welcome to remove this assert. The non fast path should be used as reference:

https://github.com/OpenNMT/OpenNMT-py/blob/0.3.0/onmt/translate/translator.py#L545

**Comment by mingchen62** [comment]
Just to confirm, the only change needed is to remove the line of assertion?
