### ISSUE TITLE
a problem found in extract_embedding.py

### ISSUE THREAD

**Issue by alphadl** [OpenNMT/OpenNMT-py#817]
I hava a question that where I can find the method(.weight) , I have checked the class Model and still can not find the method or property after word_lut . the details are as followed:

line 59    encoder_embeddings = encoder.embeddings.word_lut.weight.data.tolist()
line 60    decoder_embeddings = decoder.embeddings.word_lut.weight.data.tolist()

**Comment by pltrdy** [comment]
That's because it's not declared explicitly. 

1. `word_lut` is defined [onmt.modules.embeddings l. 153](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/embeddings.py#L153) as `self.make_embedding[0][0]`
2. `self.make_embedding` is a `Sequential` object which means that it wraps multiple modules
3. In particular, the first module is added in [line 140](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/embeddings.py#L140): `emb_luts`
4. `emb_luts` is defined in [line 124](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/embeddings.py#L124) as an [`Elementwise` object](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/util_class.py#L24) which contain `embedding`
5. `embedding` is defined in [line 122](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/embeddings.py#L122) as a list of `nn.Embedding`.
6. Therefore, `make_embedding[0][0]` is a `nn.Embedding` object.
7. Thus, `word_lut` is a `nn.Embedding` object (see point 1).
8. check [`nn.Embedding` doc](https://pytorch.org/docs/stable/nn.html?highlight=embedding#torch.nn.Embedding), it does have a `weight` parameter.
