### ISSUE TITLE
seems like the decoder is decoding the target and not the source

### ISSUE THREAD

**Issue by orrbarkat** [OpenNMT/OpenNMT-py#882]
https://github.com/OpenNMT/OpenNMT-py/blob/6b93582884a6df6417e5b9cda4e5cd3445fe1a91/onmt/decoders/decoder.py#L315

It seems like the decoders are decoding the label data and not the source/ context data. this is very weird to me.
please correct me if I don't understand the code correctly.

**Comment by twoflypig** [comment]
Hi,I think it's a method used for training process which is called teacher forcing. When training , the decoder will use the the true target of last time step as input ,it can make training quick and stable .
The another training method is to feed the input with the output of model of last time step rather than the target.
For further reading you can see  [here](https://machinelearningmastery.com/teacher-forcing-for-recurrent-neural-networks/)

**Comment by vince62s** [comment]
you may want to re-read the original paper here https://arxiv.org/pdf/1508.04025.pdf
cheers.
