### ISSUE TITLE
PR#759 for speech-music/noise discrimination

### ISSUE THREAD

**Issue by kaihuchen** [OpenNMT/OpenNMT-py#910]
@da03 
I am interested in using PR#759 for speech-music discrimination. The motivation here is that I have a whole bunch of speech audio files that I wish to transcribe into text, but many of these audios contain lead-in music or other non-speech sounds that I wish to exclude.
  
In particular, I am looking at a 'shortcut solution' like the following: 
1. Train the system to do a good job with recognizing speech based on 'clean' training data without music or other noises
2. Use this trained model to recognize an audio stream, and if the recognition confidence level is low for a segment of audio, then we can assume that this segment is what we don't want.

My question for you here is: during inferrence, how can I extract such a confidence value with timestamps on a continuous basis (e.g., confidence level is 0.21@13.40s, 0.3@14.5s, etc.)?

I understand that the simplistic method described above is unlikely to do a good job in all cases, but being able to tap into such confidence values will help me get started. Thanks!

**Comment by da03** [comment]
Hi Kaihu, in order to get the predicted probabilities, you can use the output from the generator (https://github.com/da03/OpenNMT-py/blob/speech/onmt/Loss.py#L188). However, this doesn't provide the source locations, in order to map the predictions to source timestamps, maybe you can consider using attention scores (e.g. use argmax to find the mapping from target to source). However, even if this whole process is undergone, as you noted, one potential problem with this approach is that the music and noise doesn't appear  in the training data, so there is no guarantee that at test time noise would result in a highly unlikely prediction.
