### ISSUE TITLE
Wrong usage of global attention in StdRNNDecoder ?

### ISSUE THREAD

**Issue by Frozenmad** [OpenNMT/OpenNMT-py#933]
Hi, I recently read the code under [decoder.py](https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/decoders/decoder.py), and found that the usage of attention in class **StdRNNDecoder** is strange. From its function [_run_forward_pass](https://github.com/OpenNMT/OpenNMT-py/blob/e60a54f473888d9d65bb3b5dc368a60e14c880ba/onmt/decoders/decoder.py#L195), it seems that the tgt will first go through RNN architecture [line 223](https://github.com/OpenNMT/OpenNMT-py/blob/e60a54f473888d9d65bb3b5dc368a60e14c880ba/onmt/decoders/decoder.py#L223), then calculating the [global attention](https://github.com/OpenNMT/OpenNMT-py/blob/e60a54f473888d9d65bb3b5dc368a60e14c880ba/onmt/decoders/decoder.py#L236) as the final decoder output. But in paper [NEURAL MACHINE TRANSLATION BY JOINTLY LEARNING TO ALIGN AND TRANSLATE](https://arxiv.org/pdf/1409.0473.pdf), when decoding, the global attention will be first calculated and then feed to RNN architecture to get final decoder output. It seems that other decoders also suffer from similar "mistake".

I think there is a huge difference between the architecture in code and paper, although the code's architecture can also work. Can someone explain why modifying the architecture like this ?

**Comment by vince62s** [comment]
Read this: https://github.com/tensorflow/nmt#background-on-the-attention-mechanism
might be clearer.

**Comment by pltrdy** [comment]
[Luong 2015](https://arxiv.org/pdf/1508.04025.pdf) (that is cited in @vince62s 's link), discuss that point in **sect. 3.1** > *Comparison to (Bahdanau et al.)*.

This is not a major difference in practice. Keep in mind that here will be occasions where implementations are slightly different from papers. E.g another difference with Bahdanau is that we use in OpenNMT-py so-called teacher forcing i.e. true targets are fed into the decoder instead of predictions `y_{i-1}` as suggested by Bahdanau.

**Comment by Frozenmad** [comment]
Thanks for providing the information! After reading Luong's paper, I understand this kind of attention architecture. So nice of you :)
