### ISSUE TITLE
AssertionError: assert model_dim % head_count == 0

### ISSUE THREAD

**Issue by nivranshup** [OpenNMT/OpenNMT-py#952]
I get the following error with -encoder_type transformer.

```
[2018-09-10 14:23:54,054 INFO] Loading train dataset from ./preprocess/irish-english.train.1.pt, number of examples: 1099952
[2018-09-10 14:23:55,183 INFO]  * vocabulary size. source = 50002; target = 50004
[2018-09-10 14:23:55,184 INFO] Building model...
Traceback (most recent call last):
  File "./OpenNMT-py/train.py", line 40, in <module>
    main(opt)
  File "./OpenNMT-py/train.py", line 27, in main
    single_main(opt)
  File "/home/nivpas/nmt/OpenNMT-py/onmt/train_single.py", line 104, in main
    model = build_model(model_opt, opt, fields, checkpoint)
  File "/home/nivpas/nmt/OpenNMT-py/onmt/model_builder.py", line 253, in build_model
    use_gpu(opt), checkpoint)
  File "/home/nivpas/nmt/OpenNMT-py/onmt/model_builder.py", line 166, in build_base_model
    encoder = build_encoder(model_opt, src_embeddings)
  File "/home/nivpas/nmt/OpenNMT-py/onmt/model_builder.py", line 73, in build_encoder
    opt.dropout, embeddings)
  File "/home/nivpas/nmt/OpenNMT-py/onmt/encoders/transformer.py", line 95, in __init__
    for _ in range(num_layers)])
  File "/home/nivpas/nmt/OpenNMT-py/onmt/encoders/transformer.py", line 95, in <listcomp>
    for _ in range(num_layers)])
  File "/home/nivpas/nmt/OpenNMT-py/onmt/encoders/transformer.py", line 30, in __init__
    heads, d_model, dropout=dropout)
  File "/home/nivpas/nmt/OpenNMT-py/onmt/modules/multi_headed_attn.py", line 52, in __init__
    assert model_dim % head_count == 0
AssertionError
```

Here is the command I use to run `train.py`.

```
export CUDA_VISIBLE_DEVICES=2
python ./OpenNMT-py/train.py -data ./preprocess/irish-english -save_model ./models/irish-english-transformer -encoder_type transformer -gpuid 2
```

**Comment by vince62s** [comment]
read the doc, please.
https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md

**Comment by nivranshup** [comment]
Thanks.

**Comment by jiahaosuda** [comment]
> Thanks.

I get the same error with you. 
How did you solve the problem? Thanks.

**Comment by nivranshup** [comment]
You have to set a bunch of hyperparameters with the values given here to get it working.
https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md#how-do-i-use-the-transformer-model-do-you-support-multi-gpu

**Comment by jiahaosuda** [comment]
> You have to set a bunch of hyperparameters with the values given here to get it working.
> https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md#how-do-i-use-the-transformer-model-do-you-support-multi-gpu

Thanks a lot!

**Comment by James-Decatur** [comment]
Hello,

I'm a graduate student at Indiana University and am trying to run OpenNMT on one of our supercomputers. I keep getting the same error as above, but I already made the suggested changes. Any idea what the issue could be?

The one change I made was the switch to one GPU (It runs on Google Colab just fine).

---

# new_no.yaml

# Data configurations
save_data: drive/MyDrive/MT_DATA/
src_vocab: drive/MyDrive/MT_DATA/vocab.src
tgt_vocab: drive/MyDrive/MT_DATA/vocab.tgt
save_model: drive/MyDrive/MT_DATA/
overwrite: True
data:
    corpus_1:
        path_src: drive/MyDrive/MT_DATA/train_set_11_char.txt
        path_tgt: drive/MyDrive/MT_DATA/train_set_2_char.txt
    valid:
        path_src: drive/MyDrive/MT_DATA/dev_set_11_char.txt
        path_tgt: drive/MyDrive/MT_DATA/dev_set_2_char.txt

# Training settings
save_checkpoint_steps: 10000
valid_steps: 10000
train_steps: 200000

# Batching
bucket_size: 262144
world_size: 1  # Since only one GPU is available
gpu_ranks: [0]  # Adjusted for single GPU
num_workers: 2
batch_type: "tokens"
batch_size: 4096
valid_batch_size: 2048
accum_count: [4]
accum_steps: [0]

# Optimization
model_dtype: "fp16"
optim: "adam"
learning_rate: 2
warmup_steps: 8000
decay_method: "noam"
adam_beta2: 0.998
max_grad_norm: 0
label_smoothing: 0.1
param_init: 0
param_init_glorot: true
normalization: "tokens"

# Model architecture
encoder_type: transformer
decoder_type: transformer
position_encoding: true
enc_layers: 6
dec_layers: 6
heads: 8
hidden_size: 512
word_vec_size: 512
transformer_ff: 2048
dropout_steps: [0]
dropout: [0.1]
attention_dropout: [0.1]

---
